### ISSUE TITLE
Cable help

### ISSUE THREAD

**Issue by TheWitheredStriker** [stuij/gba-serial-adventures#1]
Hey there, hoping your day is well.

I'm kinda new to this, and trying to acquire the needed equipment to use Rath; right now, I'm mainly searching for a USB-to-UART cable and a link cable. 

You mention this:
> Most of them exclude the RTS and CTS wires, and so will only expose 4 wires.
> 
> I went with the FDTI TTL-232R-3V3. You can choose between female end-points or just wires. The female endpoints can be handy if you want to debug the protocol as you can plug them on a breadboard.

I did a search for the model you mentioned, would [this one](https://benl.rs-online.com/web/p/development-tool-accessories/0429307?cm_mmc=BE-PLA-DS3A-_-google-_-CSS_BE_NL_Raspberry_Pi_%26_Arduino_%26_Development_Tools_Whoop-_-(BE:Whoop!)+Development+Tool+Accessories-_-429307&matchtype=&pla-295731484769&gclid=CjwKCAiAs8acBhA1EiwAgRFdw-UL2HFF7lJviuSQL6I1UzxoxQIfl-OcgtI_SKaG9Xhdb61XrvL8kBoCrVIQAvD_BwE&gclsrc=aw.ds) be what I need?

Also, by this:
> Again, if you're going for the full setup, you need a link cable wit at least 5 wires actually connected to the connector pins. Most aftermarket cables don't, so be ware. I've bought a few standard Japanese link cables from Ebay, and they do have five pins connected. Those Japanese link cables do miss the VCC pin, but it's not necessary for this purpose.
>
> The best way to check is to see if there are metal plates on all of the outputs. It's usually hard to see on the pictures.

You're referring to a GBA link cable, right? 

Thanks in advance for the help!

**Comment by stuij** [comment]
Hi there, yea it's a bit early in the day, but it's going pretty well.

- FDTI TTL-232R-3V3 model -> yes, that's the one
- referring to GBA link cable? -> yes, correct

Hope you get it up and running :)

**Comment by TheWitheredStriker** [comment]
Thanks! Keeping you updated on if I get it running.

**Comment by TheWitheredStriker** [comment]
One question I had: You mention that the GBA link cable is needed for the "full" setup. Would Rath be limited in use/potential without one?

**Comment by stuij** [comment]
Well, it's complicated :)

First you don't need the `full` 5-wire setup for Rath. Just having RX, TX and GND wired up is enough. You can set a variable in the Rath makefile to switch between the 3- and 5-wire setup. Practically I don't think it matters, and you could save yourself an expensive USB->UART cable.

Regarding link cable, you don't need a link cable at all if you have another method of making contact between the USB->UART cable and the GBA. You might, say, weld the cables to the contact points of the GBA link cable connector, but that's a bit messy of course. Point being that the GBA link cable doesn't do anything special. It's just a convenient way to make the wires connect properly to the GBA.

So you could get away with an aftermarket link cable that has the right pins, but I've got no clue which cable that might be. Looking at the pin schematic, you need to connect to ports 2, 3 and 6:

     _______
    / 1 3 5 \
    | 2 4 6 |	(looking at GBA cable link-port, so not GBA itself)
    '-------'

Looking at grainy pictures of aftermarket link cables, it looks like they omitted to connect to port 2 and sometimes also port 6 (?):
- https://www.ebay.co.uk/itm/255269404550
- https://www.ebay.co.uk/itm/164838208500

A better bet would be to buy an OG Gameboy (not Advance, but the old 8-bit chunker) cable:
- https://www.aliexpress.com/item/1005001458432578.html

I think they should have all the connectors and you should be able squeeze it into a GBA I believe. I did have success with an aftermarket one that could switch between GBA and Game Boy mode. I think the connector dimensions are the same except for an extra `notch` on the GBA one. But I've never tried ones specifically meant for the Game Boy, so don't hold me to it :)

Hope that helps.
