### ISSUE TITLE
Help with contact

### ISSUE THREAD

**Issue by goodtofufriday** [stuij/gba-serial-adventures#2]
So sorry to put this here but cant find any where else to contact you. Trying to get a dev with gba serial expereince to help get a project across the finish line. Commisioned work or open sourced. Have boards made and everything. I have the same username on all socials.

Again sorry to post here!

**Comment by stuij** [comment]
Hi there,

Sorry for commenting so late. I've been quite busy, and unfortunately I think I probably don't have the time right now, but I'm interested to hear about the project.
