### ISSUE TITLE
Question about pure multiboot (no flashcart)

### ISSUE THREAD

**Issue by lucasmr** [stuij/gba-serial-adventures#3]
I tested your project using a FT232R, but I wasn't able to send a multiboot binary successfully without first running your program through a flashcart. Is it possible to do a pure multiboot with UART? From what I understand, the pure multiboot uses a different protocol (Normal mode, basically SPI) and won't work with standard UART mode.

More info: https://github.com/cartr/MSMCcable

**Comment by stuij** [comment]
Hi there,

Yes, I think your understanding is correct. These UART USB cables basically serve the same purpose as the typical multiboot setup with say an Arduino do, but with the protocol being fixed to UART. It's a convenient way to interface your PC to a GBA, but I guess for pure multiboot it'd be nice to have a really small CPU to almost embed within a cable to do some proper bit banging.
